save to local storage
Thermiee/Todo-List pull request #2
Opened 2022-02-17 20:06 UTC by Thermiee

2022-02-17 23:48 UTC, brytebee requested changes
Hi, @Thermiee 👋,

Good job so far coming so far with the progress you've made! 💪💪

## Highlights
You have done amazing in the following:
- clean code✔️
- no linter errors✔️
- no console errors✔️
 
However, there are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/VL48WGMDjD64umCEkv/giphy.gif)

# Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Please, remember to tag me in your question so I can receive the notification.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-17 23:48 UTC, brytebee commented on src/index.js
> +              <h2>${todoListItem.description}</h2>
- [ ] **Required:** Your list items should have an index key. Kindly add it.

![image](https://user-images.githubusercontent.com/27709832/154589040-42b472be-6dde-44fc-94b6-ef2ceef7d7ee.png)
 
- [ ] **Required:** Kindly implement a function for editing the list item description.

- [ ] **Required:** [Kindly see the requirement for this milestone](https://github.com/microverseinc/curriculum-javascript/blob/main/todo-list/m3_add_remove.md) again for a refresher of all functionality that should be implemented.
This includes:

- ability to delete list items
- deleting an object should update the indexes of all other items.
- all changes to the To-Do List should be saved in local storage.

- [ ] **Optional:** Add an image/demo link to your project README

2022-02-19 03:10 UTC, julie-ify requested changes
## Hi @Thermiee, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-19 03:10 UTC, julie-ify commented on src/index.js
> +};
- **[REQUIRED]** It is required that newly created tasks should have the property `completed` set to false which you implemented correctly, and the property `index` set to the value of the new array length (i.e. if a 5th task is added to the list, the index of that task should equal to 5) which you haven't implemented. 

What this requirement is saying is that while creating a new task, there should be an `index` property in the object saved in the local storage. Your local storage looks like this now `{completed: false, description: "code", id: "3955fc1ab8dde", editable: false}` please make sure to add the index property to the object saved in the local storage so that your local storage looks like this `{completed: false, description: "code", id: "3955fc1ab8dde", editable: false, index:1}`. 
Please remember that the property index should be set to the value of the new array length (i.e. if a 5th task is added to the list, the index of that task should equal to 5) 

- **[REQUIRED]**  Please remember that deleting a task should update the indexes of all other items.

2022-02-19 03:10 UTC, julie-ify commented on src/index.js
> +};
- [ ] **[OPTIONAL]** Adding, removing, and editing a task works 💯 keep rocking 👍. However, let's add a line through the description once a task is checked as completed. There is a CSS property you can use to achieve this, check [here](https://www.w3schools.com/cssref/pr_text_text-decoration.asp) to learn about it. This is part of the requirement and it also improves user experience. See what I mean below:

Your Implementation | Required Implementation
:---:|:---:
![](https://camo.githubusercontent.com/1f152a6f7e241784d3c74a170825c716d3b2c0f67f8c34755e378ecfdd780c84/68747470733a2f2f692e696d6775722e636f6d2f455278554b506a2e706e67) | ![](https://camo.githubusercontent.com/e7936a63bf01bb6c704914930bc17678ef364088e4ac25cc370bccf3a02c7dac/68747470733a2f2f692e696d6775722e636f6d2f64614b543433312e706e67)

2022-02-19 11:19 UTC, Whoistolu approved these changes
### Hi @Thermiee 

Great job implementing the recommended changes.
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

# STATUS: APPROVED 🟢
**Congratulations! 🎉** 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-19 11:19 UTC, Whoistolu commented on src/index.js
> +};
👍🏽 Index works fine now

2022-02-19 15:35 UTC, moise10r approved these changes
### Hi @Thermiee , 👋 

# STATUS: Approved  🎉 

Great work on making the changes requested by a previous reviewer 👏 
 Your project is complete!  There is nothing else to say other than... it's time to merge it
Congratulations! 🎉  🎉 🎉 

![](https://media.giphy.com/media/vmtxnxveVUodG/giphy.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-19 15:41 UTC, merged